language: cpp
os:
  - osx
  - linux
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt562-trusty'
    packages:
    - qt56base
    - qt56multimedia
    - qt56tools
compiler:
  - gcc
  - clang
matrix:
  exclude:
  - os: osx
    compiler: gcc
before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then source /opt/qt56/bin/qt56-env.sh; fi
  - mkdir build
script:
  - cd build
  - qmake ../edbee-lib.pro && make -j2
  - cd edbee-test
  - ./edbee-test
